const PatientStatus = {
  REGISTERED: 'REGISTERED',
  CHECKED_IN: 'CHECKED_IN',
  WAITING_FOR_TRIAGE: 'WAITING_FOR_TRIAGE',
  TRIAGE_COMPLETE: 'TRIAGE_COMPLETE',
  WAITING_FOR_CONSULTATION: 'WAITING_FOR_CONSULTATION',
  IN_CONSULTATION: 'IN_CONSULTATION',
  CONSULTATION_COMPLETE: 'CONSULTATION_COMPLETE',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAID: 'PAID',
  DISCHARGED: 'DISCHARGED'
};

module.exports = { PatientStatus };
